pattern_cols: 10 # 标定板的列数（角点数）
pattern_rows: 7 # 行数
center_distance_mm: 15 # 标定板相邻角点的中心间距

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1] # 云台到 IMU 本体的旋转矩阵，当前是单位矩阵（无旋转）

camera_name: "galaxy"
exposure_ms: 10
gain: 10.0 # 相机增益值 低光环境增高（低增益：无噪声，画面干净）
vid_pid: "2ba2:4d55" #"2bdf:0001"

# 重投影误差: 0.0443px
camera_matrix: [1287.3790588782911, 0, 628.58157281319416, 0, 1288.4236459851522, 490.10931291092896, 0, 0, 1]
distort_coeffs: [-0.081736930045832448, 0.13686314035666389, 6.4125354366084708e-05, -0.0004338054831810324, 0]

# 相机同理想情况的偏角: yaw1.44 pitch-7.28 roll0.96 degree
# 标定板到世界坐标系原点的水平距离: 1.13 m
# 标定板同竖直摆放时的偏角: yaw7.61 pitch13.92 roll-0.46 degree
R_camera2gimbal: [-0.027182119030230909, -0.12616154330853446, 0.99163723074269183, -0.99949106557517331, 0.019998323121329122, -0.024853106601381177, -0.016695575474690555, -0.99180811252093692, -0.12664093215554434]
t_camera2gimbal: [0.13160669975045827, 0.10377721766577375, 0.024908271912914642]

# 相机同理想情况的偏角: yaw-1.22 pitch0.03 roll-0.04 degree
# 标定板到世界坐标系原点的水平距离: 0.99 m
# 标定板同竖直摆放时的偏角: yaw-176.89 pitch9.38 roll0.57 degree
# R_camera2gimbal: [-0.061623793034681837, 0.042810279869325209, -0.9971809204299531, 0.9980558453496936, 0.011981602123157308, -0.061163475815813911, 0.0093293995159397236, -0.99901137188125766, -0.043465401834097486]
# t_camera2gimbal: [-0.19467487558355218, -0.016134197484411767, 0.058813272587523231]

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"