# enemy_color: "red"
enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600
  
#####-----USB相机参数-----#####
image_width: 1920
image_height: 1080
fov_h: 87.7
fov_v: 56.7 
usb_frame_rate: 60
usb_exposure: 250 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "galaxy"
exposure_ms: 2
gamma: 0.5
vid_pid: "f622:d13a"

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15

#####-----aimer参数-----#####
yaw_offset: 0 # degree -2.5
pitch_offset: 3 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.3186px
camera_matrix: [1287.505042247567, 0, 643.17749691649203, 0, 1286.35565630977, 492.43033430561326, 0, 0, 1]
distort_coeffs: [-0.085374606930869928, 0.11854145618438121, 0.0005455228420983393, 0.0038632627091723252, 0]

# 相机同理想情况的偏角: yaw1.44 pitch-7.28 roll0.96 degree
# 标定板到世界坐标系原点的水平距离: 1.13 m
# 标定板同竖直摆放时的偏角: yaw7.61 pitch13.92 roll-0.46 degree
R_camera2gimbal: [-0.027182119030230909, -0.12616154330853446, 0.99163723074269183, -0.99949106557517331, 0.019998323121329122, -0.024853106601381177, -0.016695575474690555, -0.99180811252093692, -0.12664093215554434]
t_camera2gimbal: [0.13160669975045827, 0.10377721766577375, 0.024908271912914642]
