# enemy_color: "red"
enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 27 #67
new_fov_v: 40.9
usb_frame_rate: 120
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "galaxy"
exposure_ms: 2.0 # 曝光时间
gain: 12.0 # 增益（调大会让画面更亮，但是也会引入更大的噪声，曝光不足的时候可以调）
vid_pid: "2ba2:4d55" # USB 设备的 Vendor ID (VID) 和 Product ID (PID)

#####-----传统方法参数-----#####
threshold: 150 # 二值化阈值
max_angle_error: 45 # degree # 灯条倾斜角与期望角度的最大允许误差

# 灯条长宽比范围
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20

min_lightbar_length: 8 # 灯条最小长度（像素单位）

# 装甲板的长宽比范围
min_armor_ratio: 1
max_armor_ratio: 5
# 一块装甲板左右两条灯条长度比值的最大值
max_side_ratio: 1.5
max_rectangular_error: 25 # degree # 拟合矩形与理想矩形之间的最大误差
min_confidence: 0.8 # 置信度阈值

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "vcan0" ## can0

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 25
outpost_max_temp_lost_count: 75

#####-----pitch平滑参数-----#####
pitch_smooth_factor: 0.4

#####-----aimer参数-----#####
yaw_offset: -4.58 # degree -2.5
pitch_offset: 5.2 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
left_yaw_offset: -1
right_yaw_offset: -0.6
decision_speed: 10 # rad/s
high_speed_delay_time: 0.026 # s
low_speed_delay_time: 0.010 # s

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.0443px
camera_matrix: [1287.3790588782911, 0, 628.58157281319416, 0, 1288.4236459851522, 490.10931291092896, 0, 0, 1]
distort_coeffs: [-0.081736930045832448, 0.13686314035666389, 6.4125354366084708e-05, -0.0004338054831810324, 0]

# 相机同理想情况的偏角: yaw1.44 pitch-7.28 roll0.96 degree
# 标定板到世界坐标系原点的水平距离: 1.13 m
# 标定板同竖直摆放时的偏角: yaw7.61 pitch13.92 roll-0.46 degree
R_camera2gimbal: [-0.027182119030230909, -0.12616154330853446, 0.99163723074269183, -0.99949106557517331, 0.019998323121329122, -0.024853106601381177, -0.016695575474690555, -0.99180811252093692, -0.12664093215554434]
t_camera2gimbal: [0.13160669975045827, 0.10377721766577375, 0.024908271912914642]

# 相机同理想情况的偏角: yaw-1.22 pitch0.03 roll-0.04 degree
# 标定板到世界坐标系原点的水平距离: 0.99 m
# 标定板同竖直摆放时的偏角: yaw-176.89 pitch9.38 roll0.57 degree
# R_camera2gimbal: [-0.061623793034681837, 0.042810279869325209, -0.9971809204299531, 0.9980558453496936, 0.011981602123157308, -0.061163475815813911, 0.0093293995159397236, -0.99901137188125766, -0.043465401834097486]
# t_camera2gimbal: [-0.19467487558355218, -0.016134197484411767, 0.058813272587523231]

R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]
