# enemy_color: "red"
enemy_color: "blue"

height: 0.0
grid_num: 10
grid_size: 0.015
delay: 0

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150      # 二值化阈值	分割亮条（装甲板灯带）和背景
max_angle_error: 45 # degree 装甲板灯条角度误差阈值，过滤角度偏差过大的伪目标
min_lightbar_ratio: 1.5 # 灯条长宽比范围 过滤过粗 / 过细的伪灯条
max_lightbar_ratio: 20 
min_lightbar_length: 8 # 灯条最小像素长度	过滤过小的噪声亮点
min_armor_ratio: 1 #	装甲板整体长宽比
max_armor_ratio: 5
max_side_ratio: 1.5 # 装甲板两侧灯条比例
max_rectangular_error: 25 # degree 装甲板矩形拟合误差

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -4.58 # degree -2.5 偏航 / 俯仰补偿角度（°）
pitch_offset: 5.2 # degree 2
comming_angle: 55 # degree 目标进入 / 离开角度阈值
leaving_angle: 20 # degree
decision_speed: 7 # rad/s 决策速度
high_speed_delay_time: 0.0 # s  高低速目标的预测延迟 弹道预测补偿
low_speed_delay_time: 0.0 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "galaxy"
exposure_ms: 3
gain: 16.9
vid_pid: 2ba2:4d55 #"2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.1820px
# camera_matrix: [1785.4881526822305, 0, 672.4806478241826, 0, 1785.026019470562, 559.89603224794314, 0, 0, 1]
# distort_coeffs: [-0.076005079619881746, 0.11182817466388446, 0.0005362204787722057, -0.0027546300984895122, 0]

# 重投影误差: 0.0443px
camera_matrix: [1287.3790588782911, 0, 628.58157281319416, 0, 1288.4236459851522, 490.10931291092896, 0, 0, 1]
distort_coeffs: [-0.081736930045832448, 0.13686314035666389, 6.4125354366084708e-05, -0.0004338054831810324, 0]

# 相机同理想情况的偏角: yaw1.44 pitch-7.28 roll0.96 degree
# 标定板到世界坐标系原点的水平距离: 1.13 m
# 标定板同竖直摆放时的偏角: yaw7.61 pitch13.92 roll-0.46 degree
R_camera2gimbal: [-0.027182119030230909, -0.12616154330853446, 0.99163723074269183, -0.99949106557517331, 0.019998323121329122, -0.024853106601381177, -0.016695575474690555, -0.99180811252093692, -0.12664093215554434]
t_camera2gimbal: [0.13160669975045827, 0.10377721766577375, 0.024908271912914642]

# 相机同理想情况的偏角: yaw-1.22 pitch0.03 roll-0.04 degree
# 标定板到世界坐标系原点的水平距离: 0.99 m
# 标定板同竖直摆放时的偏角: yaw-176.89 pitch9.38 roll0.57 degree
# R_camera2gimbal: [-0.061623793034681837, 0.042810279869325209, -0.9971809204299531, 0.9980558453496936, 0.011981602123157308, -0.061163475815813911, 0.0093293995159397236, -0.99901137188125766, -0.043465401834097486]
# t_camera2gimbal: [-0.19467487558355218, -0.016134197484411767, 0.058813272587523231]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0 # 偏航 / 俯仰 PID 参数
yaw_kd: 0 # KP 调响应速度，KD 调阻尼（防抖）
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0035 # 射击阈值 云台稳定度达标才射击

max_yaw_acc: 50 # 最大角加速度	限制云台转动的加速度，避免抖振
Q_yaw: [9e6, 0] # 卡尔曼滤波 Q 矩阵	状态噪声协方差，调大则更信任预测
R_yaw: [10] # 	卡尔曼滤波 R 矩阵	观测噪声协方差，调大则更信任检测

max_pitch_acc: 50
Q_pitch: [9e6, 0]
R_pitch: [10]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s